// Autogenerated from questions 2 using parse_questions.py
const examData = [
    {
        "examId": 0,
        "title": "Exam 1: Foundations of Data Systems (Chapters 1-3)",
        "questions": [
            {
                "number": 1,
                "question": "What are the three main concerns of data-intensive applications?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Speed, cost, security"
                    },
                    {
                        "letter": "B",
                        "text": "Reliability, scalability, maintainability"
                    },
                    {
                        "letter": "C",
                        "text": "Consistency, availability, partition tolerance"
                    },
                    {
                        "letter": "D",
                        "text": "Performance, durability, availability"
                    }
                ],
                "answer": "B",
                "explanation": "Chapter 1 defines these three pillars. Reliability = working correctly through faults. Scalability = coping with increased load. Maintainability = enabling productive work by different people over time."
            },
            {
                "number": 2,
                "question": "Which of the following is NOT a standard building block for data-intensive applications?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Database"
                    },
                    {
                        "letter": "B",
                        "text": "Cache"
                    },
                    {
                        "letter": "C",
                        "text": "Load balancer"
                    },
                    {
                        "letter": "D",
                        "text": "Stream processing"
                    }
                ],
                "answer": "C",
                "explanation": "The standard building blocks are databases, caches, search indexes, stream processing, and batch processing. Load balancers are infrastructure, not a data building block."
            },
            {
                "number": 3,
                "question": "What is the difference between a fault and a failure?",
                "options": [
                    {
                        "letter": "A",
                        "text": "They are the same thing"
                    },
                    {
                        "letter": "B",
                        "text": "A fault is a component deviating from spec; a failure is the system not serving the user"
                    },
                    {
                        "letter": "C",
                        "text": "A failure is a component deviating; a fault is the system being down"
                    },
                    {
                        "letter": "D",
                        "text": "Faults are hardware; failures are software"
                    }
                ],
                "answer": "B",
                "explanation": "A fault is one component not working as expected. A failure is when the entire system stops providing the required service. Fault tolerance aims to prevent faults from becoming failures."
            },
            {
                "number": 4,
                "question": "Which type of fault causes the most outages in practice?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Hardware faults"
                    },
                    {
                        "letter": "B",
                        "text": "Software errors"
                    },
                    {
                        "letter": "C",
                        "text": "Human errors"
                    },
                    {
                        "letter": "D",
                        "text": "Network partitions"
                    }
                ],
                "answer": "C",
                "explanation": "Despite redundancy for hardware and testing for software, human errors (misconfiguration, deployment mistakes) are the largest cause of outages."
            },
            {
                "number": 5,
                "question": "Why is the average response time often misleading?",
                "options": [
                    {
                        "letter": "A",
                        "text": "It's hard to calculate"
                    },
                    {
                        "letter": "B",
                        "text": "A few slow requests can make the average look fine while many users suffer"
                    },
                    {
                        "letter": "C",
                        "text": "It doesn't include network time"
                    },
                    {
                        "letter": "D",
                        "text": "It's always higher than the median"
                    }
                ],
                "answer": "B",
                "explanation": "The average hides outliers. Using percentiles (p50, p95, p99) shows the distribution better."
            },
            {
                "number": 6,
                "question": "In the Twitter example, what is the fan-out problem?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Too many users following the same account"
                    },
                    {
                        "letter": "B",
                        "text": "A single tweet write must be distributed to millions of followers' timelines"
                    },
                    {
                        "letter": "C",
                        "text": "Too many concurrent writes to the database"
                    },
                    {
                        "letter": "D",
                        "text": "Slow search queries"
                    }
                ],
                "answer": "B",
                "explanation": "When a user tweets, it must appear in all followers' home timelines. For celebrities, this means one write becomes millions of writes."
            },
            {
                "number": 7,
                "question": "Which approach does Twitter use for celebrity accounts?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Always pre-compute timelines"
                    },
                    {
                        "letter": "B",
                        "text": "Always query on-demand"
                    },
                    {
                        "letter": "C",
                        "text": "Hybrid: pre-compute for most users, on-demand for celebrities with many followers"
                    },
                    {
                        "letter": "D",
                        "text": "Only use cache"
                    }
                ],
                "answer": "C",
                "explanation": "Pre-computing timelines for celebrities would create excessive write amplification. They use a hybrid approach."
            },
            {
                "number": 8,
                "question": "What is accidental complexity?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Complexity inherent in the problem"
                    },
                    {
                        "letter": "B",
                        "text": "Complexity arising from implementation details, not the problem itself"
                    },
                    {
                        "letter": "C",
                        "text": "Complexity from security requirements"
                    },
                    {
                        "letter": "D",
                        "text": "Complexity from scaling requirements"
                    }
                ],
                "answer": "B",
                "explanation": "Accidental complexity comes from implementation artifacts like tight coupling, tangled dependencies, and inconsistent naming, not from the actual problem being solved."
            },
            {
                "number": 9,
                "question": "What are the three principles of maintainability?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Reliability, availability, serviceability"
                    },
                    {
                        "letter": "B",
                        "text": "Operability, simplicity, evolvability"
                    },
                    {
                        "letter": "C",
                        "text": "Performance, security, usability"
                    },
                    {
                        "letter": "D",
                        "text": "Testability, deployability, monitorability"
                    }
                ],
                "answer": "B",
                "explanation": "Operability (easy ops), Simplicity (manage complexity), Evolvability (easy change)."
            },
            {
                "number": 10,
                "question": "What is the difference between vertical and horizontal scaling?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Vertical = more machines; Horizontal = bigger machine"
                    },
                    {
                        "letter": "B",
                        "text": "Vertical = bigger machine; Horizontal = more machines"
                    },
                    {
                        "letter": "C",
                        "text": "Both mean adding more machines"
                    },
                    {
                        "letter": "D",
                        "text": "Both mean upgrading CPU"
                    }
                ],
                "answer": "B",
                "explanation": "Vertical scaling = more powerful single machine. Horizontal scaling = distributing across multiple machines. Chapter 2: Data Models and Query Languages"
            },
            {
                "number": 11,
                "question": "What is the impedance mismatch?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Mismatch between CPU and memory speed"
                    },
                    {
                        "letter": "B",
                        "text": "Awkward translation between OOP objects and relational tables"
                    },
                    {
                        "letter": "C",
                        "text": "Difference between synchronous and async operations"
                    },
                    {
                        "letter": "D",
                        "text": "Mismatch between storage and network speed"
                    }
                ],
                "answer": "B",
                "explanation": "Impedance mismatch is the disconnect between object- oriented code (nested objects, inheritance) and relational databases (flat tables with rows/columns)."
            },
            {
                "number": 12,
                "question": "Which data model is best for data with complex many-to-many relationships?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Document model"
                    },
                    {
                        "letter": "B",
                        "text": "Relational model"
                    },
                    {
                        "letter": "C",
                        "text": "Graph model"
                    },
                    {
                        "letter": "D",
                        "text": "Key-value model"
                    }
                ],
                "answer": "C",
                "explanation": "Graph models excel at many-to-many relationships where connections are as important as the data itself."
            },
            {
                "number": 13,
                "question": "What is normalization in database design?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Making data denormalized for performance"
                    },
                    {
                        "letter": "B",
                        "text": "Removing duplicate data by storing IDs instead of full values"
                    },
                    {
                        "letter": "C",
                        "text": "Creating indexes for faster queries"
                    },
                    {
                        "letter": "D",
                        "text": "Splitting tables across multiple servers"
                    }
                ],
                "answer": "B",
                "explanation": "Normalization replaces repeated values with IDs pointing to a canonical definition, ensuring consistency and a single source of truth."
            },
            {
                "number": 14,
                "question": "What is the key difference between declarative and imperative query languages?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Declarative specifies what result to produce; imperative specifies how to compute it"
                    },
                    {
                        "letter": "B",
                        "text": "Declarative is faster"
                    },
                    {
                        "letter": "C",
                        "text": "Imperative is always SQL"
                    },
                    {
                        "letter": "D",
                        "text": "There is no real difference"
                    }
                ],
                "answer": "A",
                "explanation": "Declarative (SQL) says what you want; the query optimizer figures out how. Imperative spells out exact steps."
            },
            {
                "number": 15,
                "question": "What does a MapReduce job consist of?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Map and Collect phases"
                    },
                    {
                        "letter": "B",
                        "text": "Map and Reduce phases"
                    },
                    {
                        "letter": "C",
                        "text": "Sort and Search phases"
                    },
                    {
                        "letter": "D",
                        "text": "Read and Write phases"
                    }
                ],
                "answer": "B",
                "explanation": "Map extracts relevant data; Reduce aggregates it."
            },
            {
                "number": 16,
                "question": "Which of the following is a declarative query language?",
                "options": [
                    {
                        "letter": "A",
                        "text": "JavaScript"
                    },
                    {
                        "letter": "B",
                        "text": "Java"
                    },
                    {
                        "letter": "C",
                        "text": "Cypher"
                    },
                    {
                        "letter": "D",
                        "text": "Assembly"
                    }
                ],
                "answer": "C",
                "explanation": "Cypher (Neo4j) is declarative — you specify patterns, not traversal algorithms."
            },
            {
                "number": 17,
                "question": "What is a property graph?",
                "options": [
                    {
                        "letter": "A",
                        "text": "A graph where edges have no direction"
                    },
                    {
                        "letter": "B",
                        "text": "A graph with vertices and edges that can have properties (key-value pairs)"
                    },
                    {
                        "letter": "C",
                        "text": "Only vertices have properties"
                    },
                    {
                        "letter": "D",
                        "text": "A graph stored in a relational database"
                    }
                ],
                "answer": "B",
                "explanation": "In property graphs, both vertices and edges can have properties."
            },
            {
                "number": 18,
                "question": "When should you consider a document database?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Data has complex many-to-many relationships"
                    },
                    {
                        "letter": "B",
                        "text": "Data is self-contained with one-to-many tree structures"
                    },
                    {
                        "letter": "C",
                        "text": "You need ACID transactions across many records"
                    },
                    {
                        "letter": "D",
                        "text": "You need complex joins"
                    }
                ],
                "answer": "B",
                "explanation": "Document databases are good for document-like self- contained data with one-to-many structures and flexible schema."
            },
            {
                "number": 19,
                "question": "What is SPARQL?",
                "options": [
                    {
                        "letter": "A",
                        "text": "A SQL extension for graph queries"
                    },
                    {
                        "letter": "B",
                        "text": "A query language for RDF triple-stores"
                    },
                    {
                        "letter": "C",
                        "text": "A protocol for stream processing"
                    },
                    {
                        "letter": "D",
                        "text": "A MapReduce implementation"
                    }
                ],
                "answer": "B",
                "explanation": "SPARQL is a query language for RDF triple-stores, used in Semantic Web applications."
            },
            {
                "number": 20,
                "question": "In the context of query languages, what is Datalog?",
                "options": [
                    {
                        "letter": "A",
                        "text": "A NoSQL database"
                    },
                    {
                        "letter": "B",
                        "text": "A foundation for query languages using rules and predicates"
                    },
                    {
                        "letter": "C",
                        "text": "A binary encoding format"
                    },
                    {
                        "letter": "D",
                        "text": "A replication protocol"
                    }
                ],
                "answer": "B",
                "explanation": "Datalog is a declarative logic programming language that serves as the foundation for many query languages, using rules to define new predicates from existing facts. Chapter 3: Storage and Retrieval"
            },
            {
                "number": 21,
                "question": "What is a hash index?",
                "options": [
                    {
                        "letter": "A",
                        "text": "An index that stores values in sorted order"
                    },
                    {
                        "letter": "B",
                        "text": "An in-memory hash map where keys map to byte offsets in a data file"
                    },
                    {
                        "letter": "C",
                        "text": "An index that supports range queries"
                    },
                    {
                        "letter": "D",
                        "text": "A B-Tree variant"
                    }
                ],
                "answer": "B",
                "explanation": "Hash indexes use an in-memory hash map mapping keys to byte offsets in an append-only log file."
            },
            {
                "number": 22,
                "question": "What is a major limitation of hash indexes?",
                "options": [
                    {
                        "letter": "A",
                        "text": "They don't support point lookups"
                    },
                    {
                        "letter": "B",
                        "text": "They must fit entirely in memory"
                    },
                    {
                        "letter": "C",
                        "text": "They are slow for writes"
                    },
                    {
                        "letter": "D",
                        "text": "They can't handle duplicate keys"
                    }
                ],
                "answer": "B",
                "explanation": "The hash map must fit in RAM. Also, range queries are inefficient since keys aren't ordered."
            },
            {
                "number": 23,
                "question": "What advantage do SSTables have over unsorted log files with hash indexes?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Keys are sorted, enabling efficient merging and sparse indexes"
                    },
                    {
                        "letter": "B",
                        "text": "They are always smaller"
                    },
                    {
                        "letter": "C",
                        "text": "They don't need compaction"
                    },
                    {
                        "letter": "D",
                        "text": "They support in-place updates"
                    }
                ],
                "answer": "A",
                "explanation": "SSTables store keys in sorted order, allowing efficient mergesort-style merging and sparse in-memory indexes with binary search."
            },
            {
                "number": 24,
                "question": "How does an LSM-Tree handle writes?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Write directly to disk"
                    },
                    {
                        "letter": "B",
                        "text": "Write to an in-memory memtable, then flush to disk as SSTable"
                    },
                    {
                        "letter": "C",
                        "text": "Write to a B-Tree"
                    },
                    {
                        "letter": "D",
                        "text": "Write to a hash table"
                    }
                ],
                "answer": "B",
                "explanation": "Writes go to an in-memory balanced tree (memtable). When full, it's flushed to disk as an immutable SSTable."
            },
            {
                "number": 25,
                "question": "What is a write-ahead log (WAL) used for?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Speeding up reads"
                    },
                    {
                        "letter": "B",
                        "text": "Crash recovery by recording writes before applying them"
                    },
                    {
                        "letter": "C",
                        "text": "Compressing data"
                    },
                    {
                        "letter": "D",
                        "text": "Indexing data"
                    }
                ],
                "answer": "B",
                "explanation": "WAL is an append-only log of all writes, used to restore the database to a consistent state after a crash."
            },
            {
                "number": 26,
                "question": "Which is better for write-heavy workloads — B-Trees or LSM-Trees?",
                "options": [
                    {
                        "letter": "A",
                        "text": "B-Trees"
                    },
                    {
                        "letter": "B",
                        "text": "LSM-Trees"
                    },
                    {
                        "letter": "C",
                        "text": "Both are equal"
                    },
                    {
                        "letter": "D",
                        "text": "Neither"
                    }
                ],
                "answer": "B",
                "explanation": "LSM-Trees are append-only with sequential disk I/O, making writes much faster than B-Trees' in-place page updates."
            },
            {
                "number": 27,
                "question": "What is the difference between OLTP and OLAP?",
                "options": [
                    {
                        "letter": "A",
                        "text": "OLTP is for analytics; OLAP is for transactions"
                    },
                    {
                        "letter": "B",
                        "text": "OLTP handles day-to-day transactions; OLAP handles analytical queries"
                    },
                    {
                        "letter": "C",
                        "text": "They are the same thing"
                    },
                    {
                        "letter": "D",
                        "text": "OLTP uses column stores; OLAP uses row stores"
                    }
                ],
                "answer": "B",
                "explanation": "OLTP: small random access, many users, point queries. OLAP: large scans, aggregations, few users."
            },
            {
                "number": 28,
                "question": "What is column-oriented storage?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Storing entire rows together"
                    },
                    {
                        "letter": "B",
                        "text": "Storing each column's values contiguously"
                    },
                    {
                        "letter": "C",
                        "text": "A type of B-Tree"
                    },
                    {
                        "letter": "D",
                        "text": "An in-memory database"
                    }
                ],
                "answer": "B",
                "explanation": "Column stores group values from the same column together, enabling loading only needed columns for analytical queries."
            },
            {
                "number": 29,
                "question": "What is a data cube (OLAP cube)?",
                "options": [
                    {
                        "letter": "A",
                        "text": "A 3D visualization of data"
                    },
                    {
                        "letter": "B",
                        "text": "Pre-computed aggregation grouped by multiple dimensions"
                    },
                    {
                        "letter": "C",
                        "text": "A type of NoSQL database"
                    },
                    {
                        "letter": "D",
                        "text": "A hardware storage device"
                    }
                ],
                "answer": "B",
                "explanation": "Data cubes pre-compute aggregates (e.g., total sales by date, product, store) for fast query responses."
            },
            {
                "number": 30,
                "question": "What is a Bloom filter used for in LSM-Trees?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Compressing SSTables"
                    },
                    {
                        "letter": "B",
                        "text": "Quickly checking if a key might exist without reading disk"
                    },
                    {
                        "letter": "C",
                        "text": "Sorting data in memtable"
                    },
                    {
                        "letter": "D",
                        "text": "Encrypting data"
                    }
                ],
                "answer": "B",
                "explanation": "Bloom filters provide a fast probabilistic check for key existence, avoiding unnecessary disk reads for non-existent keys. Chapter 4: Encoding and Evolution"
            }
        ]
    },
    {
        "examId": 1,
        "title": "Exam 2: Distributed Data & Replication (Chapters 4-5)",
        "questions": [
            {
                "number": 31,
                "question": "What is backward compatibility?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Old code can read data written by new code"
                    },
                    {
                        "letter": "B",
                        "text": "New code can read data written by old code"
                    },
                    {
                        "letter": "C",
                        "text": "Data can be read across different programming languages"
                    },
                    {
                        "letter": "D",
                        "text": "Data can be read by different database versions"
                    }
                ],
                "answer": "B",
                "explanation": "Backward compatibility = new code can read old data. Forward compatibility = old code can read new data."
            },
            {
                "number": 32,
                "question": "How do Thrift and Protocol Buffers identify fields in encoded data?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Using field names"
                    },
                    {
                        "letter": "B",
                        "text": "Using field tag numbers"
                    },
                    {
                        "letter": "C",
                        "text": "Using field positions"
                    },
                    {
                        "letter": "D",
                        "text": "Using field hashes"
                    }
                ],
                "answer": "B",
                "explanation": "Both use numeric field tags instead of names for compact encoding. Tags cannot be changed after deployment."
            },
            {
                "number": 33,
                "question": "What happens if you change a field's tag number in Protocol Buffers?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Nothing — it's fine"
                    },
                    {
                        "letter": "B",
                        "text": "All existing encoded data becomes invalid"
                    },
                    {
                        "letter": "C",
                        "text": "Performance improves"
                    },
                    {
                        "letter": "D",
                        "text": "The field becomes required"
                    }
                ],
                "answer": "B",
                "explanation": "Encoded data uses tag numbers to identify fields. Changing a tag breaks all data encoded with the old schema."
            },
            {
                "number": 34,
                "question": "What is unique about Avro's approach to schema evolution?",
                "options": [
                    {
                        "letter": "A",
                        "text": "It uses tag numbers like Protobuf"
                    },
                    {
                        "letter": "B",
                        "text": "It resolves writer's schema and reader's schema at read time, matching fields by name"
                    },
                    {
                        "letter": "C",
                        "text": "It doesn't support schema evolution"
                    },
                    {
                        "letter": "D",
                        "text": "It requires identical schemas on both ends"
                    }
                ],
                "answer": "B",
                "explanation": "Avro matches fields by name between writer and reader schemas at read time, without requiring tag numbers."
            },
            {
                "number": 35,
                "question": "What is required to add a field in Avro while maintaining compatibility?",
                "options": [
                    {
                        "letter": "A",
                        "text": "It must have a default value"
                    },
                    {
                        "letter": "B",
                        "text": "It must have a unique tag number"
                    },
                    {
                        "letter": "C",
                        "text": "It must be marked required"
                    },
                    {
                        "letter": "D",
                        "text": "It must be added at the end"
                    }
                ],
                "answer": "A",
                "explanation": "New fields in Avro need default values so old readers can fill them in, and old writers can have them filled in by new readers."
            },
            {
                "number": 36,
                "question": "Why is Avro better suited for dynamically generated schemas than Thrift or Protobuf?",
                "options": [
                    {
                        "letter": "A",
                        "text": "It's faster"
                    },
                    {
                        "letter": "B",
                        "text": "It doesn't need tag numbers, so schemas can be auto-generated (e.g., from database tables)"
                    },
                    {
                        "letter": "C",
                        "text": "It supports more data types"
                    },
                    {
                        "letter": "D",
                        "text": "It uses JSON for encoding"
                    }
                ],
                "answer": "B",
                "explanation": "Without tag numbers, Avro schemas can be generated automatically from database schemas without manual tag assignment."
            },
            {
                "number": 37,
                "question": "Which is NOT a valid mode of dataflow discussed in Chapter 4?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Via databases"
                    },
                    {
                        "letter": "B",
                        "text": "Via service calls (REST/RPC)"
                    },
                    {
                        "letter": "C",
                        "text": "Via file system (NFS)"
                    },
                    {
                        "letter": "D",
                        "text": "Via asynchronous message passing"
                    }
                ],
                "answer": "C",
                "explanation": "The three modes are: databases, service calls (REST/RPC), and asynchronous message passing (message brokers/actors)."
            },
            {
                "number": 38,
                "question": "What is the \"data outlives code\" problem?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Code is slower than data transfer"
                    },
                    {
                        "letter": "B",
                        "text": "Old data persists in original encoding long after code has changed"
                    },
                    {
                        "letter": "C",
                        "text": "Data files are too large for the code"
                    },
                    {
                        "letter": "D",
                        "text": "Code crashes when reading old data"
                    }
                ],
                "answer": "B",
                "explanation": "Data in databases may have been written years ago and still exists in its original encoding, even after many code deployments."
            },
            {
                "number": 39,
                "question": "Why is RPC fundamentally different from a local function call?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Network latency is unpredictable"
                    },
                    {
                        "letter": "B",
                        "text": "Timeouts may leave the caller unsure if operation completed"
                    },
                    {
                        "letter": "C",
                        "text": "Retries can cause duplicate operations"
                    },
                    {
                        "letter": "D",
                        "text": "All of the above"
                    }
                ],
                "answer": "D",
                "explanation": "Network calls introduce unpredictability, timeouts, variable latency, the need for encoding, and idempotence concerns — all absent from local calls."
            },
            {
                "number": 40,
                "question": "What advantage does a message broker provide over direct RPC?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Lower latency"
                    },
                    {
                        "letter": "B",
                        "text": "Acts as buffer if recipient is unavailable; decouples sender from recipient"
                    },
                    {
                        "letter": "C",
                        "text": "Guarantees exactly-once delivery"
                    },
                    {
                        "letter": "D",
                        "text": "No network needed"
                    }
                ],
                "answer": "B",
                "explanation": "Message brokers buffer messages during outages, auto- redeliver, hide IP details, and decouple producers from consumers. Chapter 5: Replication"
            },
            {
                "number": 41,
                "question": "What are the three main replication algorithms discussed?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Active, passive, hybrid"
                    },
                    {
                        "letter": "B",
                        "text": "Single-leader, multi-leader, leaderless"
                    },
                    {
                        "letter": "C",
                        "text": "Synchronous, asynchronous, semi-synchronous"
                    },
                    {
                        "letter": "D",
                        "text": "Horizontal, vertical, diagonal"
                    }
                ],
                "answer": "B",
                "explanation": "The three approaches are: single-leader (one write node), multi-leader (multiple write nodes), and leaderless (any node accepts writes)."
            },
            {
                "number": 42,
                "question": "In leader-based replication, where can writes be sent?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Any replica"
                    },
                    {
                        "letter": "B",
                        "text": "Only the leader"
                    },
                    {
                        "letter": "C",
                        "text": "Only followers"
                    },
                    {
                        "letter": "D",
                        "text": "Any node in the cluster"
                    }
                ],
                "answer": "B",
                "explanation": "Only the leader accepts writes. Followers are read-only from the client's perspective."
            },
            {
                "number": 43,
                "question": "What is semi-synchronous replication?",
                "options": [
                    {
                        "letter": "A",
                        "text": "All followers are synchronous"
                    },
                    {
                        "letter": "B",
                        "text": "One follower is synchronous; others are asynchronous"
                    },
                    {
                        "letter": "C",
                        "text": "Replication happens every few seconds"
                    },
                    {
                        "letter": "D",
                        "text": "Only half the data is replicated"
                    }
                ],
                "answer": "B",
                "explanation": "Semi-sync ensures at least one follower has up-to-date data (leader + one sync follower), balancing durability with performance."
            },
            {
                "number": 44,
                "question": "What is the risk of fully asynchronous replication?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Reads are always stale"
                    },
                    {
                        "letter": "B",
                        "text": "Writes confirmed to client may be lost if leader fails"
                    },
                    {
                        "letter": "C",
                        "text": "Followers can't serve reads"
                    },
                    {
                        "letter": "D",
                        "text": "Network bandwidth is wasted"
                    }
                ],
                "answer": "B",
                "explanation": "With async replication, if the leader crashes before replicating, acknowledged writes are lost."
            },
            {
                "number": 45,
                "question": "Which replication log method is most tightly coupled to the storage engine?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Statement-based"
                    },
                    {
                        "letter": "B",
                        "text": "WAL shipping"
                    },
                    {
                        "letter": "C",
                        "text": "Logical (row-based)"
                    },
                    {
                        "letter": "D",
                        "text": "Trigger-based"
                    }
                ],
                "answer": "B",
                "explanation": "WAL shipping sends the storage engine's physical log, tightly coupling leader and follower to the same DB version."
            },
            {
                "number": 46,
                "question": "Which of these is NOT a problem caused by replication lag?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Read-after-write inconsistency"
                    },
                    {
                        "letter": "B",
                        "text": "Monotonic read violation"
                    },
                    {
                        "letter": "C",
                        "text": "Consistent prefix violation"
                    },
                    {
                        "letter": "D",
                        "text": "Network partition"
                    }
                ],
                "answer": "D",
                "explanation": "Network partition is a cause, not a symptom of replication lag. The three anomalies are read-after-write, monotonic reads, and consistent prefix reads."
            },
            {
                "number": 47,
                "question": "What guarantee does read-after-write consistency provide?",
                "options": [
                    {
                        "letter": "A",
                        "text": "All users see all writes immediately"
                    },
                    {
                        "letter": "B",
                        "text": "A user always sees their own submitted writes"
                    },
                    {
                        "letter": "C",
                        "text": "Reads never return stale data"
                    },
                    {
                        "letter": "D",
                        "text": "Writes are immediately visible to all users"
                    }
                ],
                "answer": "B",
                "explanation": "Read-after-write (read-your-writes) guarantees a user sees what they themselves submitted, but makes no promises about other users' writes."
            },
            {
                "number": 48,
                "question": "What is the simplest way to achieve monotonic reads?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Read from the leader every time"
                    },
                    {
                        "letter": "B",
                        "text": "Route each user to the same replica consistently"
                    },
                    {
                        "letter": "C",
                        "text": "Use synchronous replication"
                    },
                    {
                        "letter": "D",
                        "text": "Disable caching"
                    }
                ],
                "answer": "B",
                "explanation": "By hashing user ID to choose a replica, users see a consistent view without time going backward."
            },
            {
                "number": 49,
                "question": "When is multi-leader replication most appropriate?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Single-datacenter deployment"
                    },
                    {
                        "letter": "B",
                        "text": "Multi-datacenter operation with local writes"
                    },
                    {
                        "letter": "C",
                        "text": "When strong consistency is required"
                    },
                    {
                        "letter": "D",
                        "text": "When there is no network between nodes"
                    }
                ],
                "answer": "B",
                "explanation": "Multi-leader is useful for multi-datacenter setups where each location has its own leader for low-latency local writes."
            },
            {
                "number": 50,
                "question": "What is the biggest downside of multi-leader replication?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Poor read scalability"
                    },
                    {
                        "letter": "B",
                        "text": "Write conflicts that must be resolved"
                    },
                    {
                        "letter": "C",
                        "text": "No failover mechanism"
                    },
                    {
                        "letter": "D",
                        "text": "Requires more hardware"
                    }
                ],
                "answer": "B",
                "explanation": "Concurrent writes on different leaders to the same data create conflicts that need resolution, adding complexity."
            },
            {
                "number": 51,
                "question": "What does the quorum condition w + r > n guarantee?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Strong consistency"
                    },
                    {
                        "letter": "B",
                        "text": "At least one node in the read set has the latest write"
                    },
                    {
                        "letter": "C",
                        "text": "No data loss"
                    },
                    {
                        "letter": "D",
                        "text": "Linearizability"
                    }
                ],
                "answer": "B",
                "explanation": "With w + r > n, the read set must overlap with the write set, ensuring at least one node returns the latest value."
            },
            {
                "number": 52,
                "question": "What is read repair in leaderless replication?",
                "options": [
                    {
                        "letter": "A",
                        "text": "A background process that fixes stale data"
                    },
                    {
                        "letter": "B",
                        "text": "The client detects stale replicas during reads and writes the newer value back"
                    },
                    {
                        "letter": "C",
                        "text": "A logging mechanism"
                    },
                    {
                        "letter": "D",
                        "text": "A type of index"
                    }
                ],
                "answer": "B",
                "explanation": "When a client reads from multiple replicas and finds a stale value, it writes the newer value back to that replica."
            },
            {
                "number": 53,
                "question": "What is a sloppy quorum?",
                "options": [
                    {
                        "letter": "A",
                        "text": "A quorum that doesn't require a majority"
                    },
                    {
                        "letter": "B",
                        "text": "When w + r ≤ n"
                    },
                    {
                        "letter": "C",
                        "text": "Accepting writes from nodes outside the designated n home nodes during network issues"
                    },
                    {
                        "letter": "D",
                        "text": "A quorum that uses timestamps"
                    }
                ],
                "answer": "C",
                "explanation": "Sloppy quorums accept writes on any available node when the designated n home nodes are unreachable."
            },
            {
                "number": 54,
                "question": "What is \"last write wins\" (LWW) and why is it dangerous?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Wins the last write; safe for all workloads"
                    },
                    {
                        "letter": "B",
                        "text": "Keeps the highest-timestamped write; silently discards concurrent writes"
                    },
                    {
                        "letter": "C",
                        "text": "Prevents concurrent writes; guarantees no data loss"
                    },
                    {
                        "letter": "D",
                        "text": "Resolves conflicts through voting; slow but safe"
                    }
                ],
                "answer": "B",
                "explanation": "LWW picks the highest timestamp and discards others. Concurrent writes, even successful ones, are silently lost."
            },
            {
                "number": 55,
                "question": "What are version vectors used for?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Compressing replicated data"
                    },
                    {
                        "letter": "B",
                        "text": "Tracking which version of a key each replica has to detect concurrency"
                    },
                    {
                        "letter": "C",
                        "text": "Routing requests to the correct replica"
                    },
                    {
                        "letter": "D",
                        "text": "Encrypting data for replication"
                    }
                ],
                "answer": "B",
                "explanation": "Version vectors track per-replica version numbers per key, letting the system distinguish overwrites from concurrent writes. Cross-Chapter Questions"
            },
            {
                "number": 56,
                "question": "Which storage engine (Ch3) combined with which replication method (Ch5) is least suitable for rolling upgrades?",
                "options": [
                    {
                        "letter": "A",
                        "text": "LSM-Tree + logical replication"
                    },
                    {
                        "letter": "B",
                        "text": "B-Tree + WAL shipping"
                    },
                    {
                        "letter": "C",
                        "text": "Hash index + statement replication"
                    },
                    {
                        "letter": "D",
                        "text": "Column store + trigger replication"
                    }
                ],
                "answer": "B",
                "explanation": "WAL shipping is tightly coupled to the storage engine version. B-Tree WAL format changes between DB versions, preventing leader/follower from running different versions."
            },
            {
                "number": 57,
                "question": "An application needs high write throughput, flexible schema, and must scale reads. Which combination of choices from chapters 2-5 is most appropriate?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Relational + B-Tree + single-leader"
                    },
                    {
                        "letter": "B",
                        "text": "Document + LSM-Tree + leaderless"
                    },
                    {
                        "letter": "C",
                        "text": "Graph + Hash index + multi-leader"
                    },
                    {
                        "letter": "D",
                        "text": "Relational + Column store + WAL shipping"
                    }
                ],
                "answer": "B",
                "explanation": "Document model offers flexible schema (Ch2). LSM-Trees excel at write-heavy workloads (Ch3). Leaderless replication scales reads and handles node failures (Ch5)."
            },
            {
                "number": 58,
                "question": "What do hash indexes (Ch3) and Avro binary encoding (Ch4) have in common?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Both support range queries"
                    },
                    {
                        "letter": "B",
                        "text": "Both use field names"
                    },
                    {
                        "letter": "C",
                        "text": "Both must fit in memory"
                    },
                    {
                        "letter": "D",
                        "text": "Both are efficient for their purpose but have trade-offs: hash indexes can't do range queries; Avro needs reader+writer schema resolution"
                    }
                ],
                "answer": "D",
                "explanation": "Both are optimized for specific use cases but have limitations — hash indexes lack ordering, Avro requires both schemas at read time."
            },
            {
                "number": 59,
                "question": "A banking system requires strong consistency and strict schema. Which choices from chapters 2-5 align best?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Document model + LSM-Tree + leaderless replication"
                    },
                    {
                        "letter": "B",
                        "text": "Relational model + B-Tree + single-leader synchronous replication"
                    },
                    {
                        "letter": "C",
                        "text": "Graph model + Hash index + multi-leader"
                    },
                    {
                        "letter": "D",
                        "text": "Document model + Column store + async single-leader"
                    }
                ],
                "answer": "B",
                "explanation": "Relational provides strict schemas (Ch2). B-Trees offer simpler consistency (Ch3). Single-leader with sync replication ensures no data loss and strong consistency (Ch5)."
            },
            {
                "number": 60,
                "question": "What is the relationship between schema evolution (Ch4) and replication (Ch5)?",
                "options": [
                    {
                        "letter": "A",
                        "text": "No relationship"
                    },
                    {
                        "letter": "B",
                        "text": "Schema evolution enables rolling upgrades, which require backward/ forward compatible replication log formats"
                    },
                    {
                        "letter": "C",
                        "text": "Replication prevents schema evolution"
                    },
                    {
                        "letter": "D",
                        "text": "Schema evolution only matters for single-node databases"
                    }
                ],
                "answer": "B",
                "explanation": "Rolling upgrades require different nodes to run different versions simultaneously. The replication log format must be backward/ forward compatible (Ch4) for followers running different code versions than the leader (Ch5)."
            },
            {
                "number": 61,
                "question": "Twitter's fan-out problem (Ch1) is an example of which replication challenge (Ch5)?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Split brain"
                    },
                    {
                        "letter": "B",
                        "text": "Write amplification — one tweet becomes many timeline writes"
                    },
                    {
                        "letter": "C",
                        "text": "Read repair"
                    },
                    {
                        "letter": "D",
                        "text": "Consistent prefix violation"
                    }
                ],
                "answer": "B",
                "explanation": "One write (tweet) fanned out to millions of followers' timelines is a classic write amplification scenario."
            },
            {
                "number": 62,
                "question": "Which consistency model (Ch1) is most relevant to the replication lag anomaly where a user sees their comment disappear (Ch5)?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Reliability"
                    },
                    {
                        "letter": "B",
                        "text": "Maintainability"
                    },
                    {
                        "letter": "C",
                        "text": "Monotonic reads"
                    },
                    {
                        "letter": "D",
                        "text": "Throughput"
                    }
                ],
                "answer": "C",
                "explanation": "When a user sees data from a fresh replica then from a stale replica, the data appears to disappear — a monotonic read violation."
            },
            {
                "number": 63,
                "question": "The \"data outlives code\" problem (Ch4) is most relevant to which aspect of replication (Ch5)?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Failover"
                    },
                    {
                        "letter": "B",
                        "text": "Schema evolution for databases — old data remains in original encoding"
                    },
                    {
                        "letter": "C",
                        "text": "Quorum configuration"
                    },
                    {
                        "letter": "D",
                        "text": "Multi-leader conflict resolution"
                    }
                ],
                "answer": "B",
                "explanation": "Data written years ago in old formats must be readable by current code. This requires backward-compatible encoding (Ch4) and affects database replication where old records persist (Ch5)."
            },
            {
                "number": 64,
                "question": "A startup needs to evolve its data schema frequently. Which encoding and replication approach best supports this?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Thrift + single-leader WAL shipping"
                    },
                    {
                        "letter": "B",
                        "text": "Avro + logical (row-based) replication"
                    },
                    {
                        "letter": "C",
                        "text": "JSON + trigger-based replication"
                    },
                    {
                        "letter": "D",
                        "text": "Protocol Buffers + statement-based replication"
                    }
                ],
                "answer": "B",
                "explanation": "Avro's name-based schema evolution (Ch4) supports frequent schema changes without tag management. Logical replication (Ch5) allows leader/follower version mismatches."
            },
            {
                "number": 65,
                "question": "Which of the following correctly orders the chapters' progression from most abstract to most concrete?",
                "options": [
                    {
                        "letter": "A",
                        "text": "Ch3 (storage) → Ch4 (encoding) → Ch5 (replication) → Ch2 (data models) → Ch1 (design goals)"
                    },
                    {
                        "letter": "B",
                        "text": "Ch1 (goals) → Ch2 (models) → Ch3 (storage) → Ch4 (encoding) → Ch5 (distributed replication)"
                    },
                    {
                        "letter": "C",
                        "text": "Ch5 → Ch4 → Ch3 → Ch2 → Ch1"
                    },
                    {
                        "letter": "D",
                        "text": "Ch2 → Ch1 → Ch4 → Ch3 → Ch5"
                    }
                ],
                "answer": "B",
                "explanation": "The book moves from high-level concerns (reliability, scalability) → data models → storage engines → encoding → distributed data/replication."
            }
        ]
    },
    {
        "examId": 2,
        "title": "Exam 3: Comparisons & Deep Analysis (Chapters 1-5)",
        "questions": [
            {
                "number": 65,
                "type": "comparison",
                "question": "Compare B-Trees vs LSM-Trees across the following dimensions:",
                "comparisonData": {
                    "headers": ["Aspect", "B-Trees", "LSM-Trees"],
                    "rows": [
                        ["Write Performance", "Slower — random in-place page writes", "Faster — sequential append-only writes to memtable then disk"],
                        ["Read Performance", "Faster — single tree traversal, O(log n)", "Slower — may check memtable + multiple SSTables"],
                        ["Write Amplification", "Higher — page splits, WAL + page write", "Lower per write but compaction adds background I/O"],
                        ["Space Amplification", "Lower — no duplicate keys", "Higher — multiple versions until compaction"],
                        ["Concurrency", "Complex — requires latches on pages", "Simpler — immutable SSTables, only memtable needs locking"],
                        ["Use Case", "OLTP with balanced read/write", "Write-heavy workloads, time-series, logs"]
                    ]
                },
                "followUpQuestion": "In which scenario would you choose B-Trees over LSM-Trees?",
                "options": [
                    {"letter": "A", "text": "Write-heavy logging system with sequential access patterns"},
                    {"letter": "B", "text": "Transaction processing system requiring strong read consistency and low read latency"},
                    {"letter": "C", "text": "Time-series database ingesting millions of sensor readings per second"},
                    {"letter": "D", "text": "A cache layer that mostly handles key-value insertions"}
                ],
                "answer": "B",
                "explanation": "B-Trees provide faster reads since keys exist in exactly one location, making them ideal for OLTP systems where read latency and transaction consistency matter more than raw write throughput."
            },
            {
                "number": 66,
                "type": "comparison",
                "question": "Compare Single-Leader vs Multi-Leader vs Leaderless replication:",
                "comparisonData": {
                    "headers": ["Aspect", "Single-Leader", "Multi-Leader", "Leaderless"],
                    "rows": [
                        ["Write Nodes", "One leader only", "Multiple leaders (one per datacenter)", "Any node accepts writes"],
                        ["Consistency", "Strong (synchronous) or eventual (async)", "Eventual — conflicts must be resolved", "Eventual — quorum-based guarantees"],
                        ["Conflict Handling", "No write conflicts (single writer)", "Must detect and resolve conflicts", "Uses version vectors / LWW"],
                        ["Latency", "Higher for cross-DC writes", "Low local writes per DC", "Low — write to nearest nodes"],
                        ["Fault Tolerance", "Failover required if leader fails", "Tolerates individual DC failures", "Tolerates individual node failures"],
                        ["Complexity", "Simplest to implement", "High — conflict resolution logic", "Medium — quorum configuration"]
                    ]
                },
                "followUpQuestion": "A global e-commerce company needs local writes in each datacenter with eventual consistency. Which replication model fits best?",
                "options": [
                    {"letter": "A", "text": "Single-leader with synchronous followers"},
                    {"letter": "B", "text": "Multi-leader replication with one leader per datacenter"},
                    {"letter": "C", "text": "Leaderless replication with sloppy quorums"},
                    {"letter": "D", "text": "Single-leader with read replicas only"}
                ],
                "answer": "B",
                "explanation": "Multi-leader replication allows each datacenter to have its own leader, enabling low-latency local writes while replicating asynchronously across datacenters. This is ideal for global operations where each region needs autonomous write capability."
            },
            {
                "number": 67,
                "type": "comparison",
                "question": "Compare encoding formats: JSON vs Protocol Buffers vs Avro:",
                "comparisonData": {
                    "headers": ["Aspect", "JSON", "Protocol Buffers", "Avro"],
                    "rows": [
                        ["Format", "Text-based, human-readable", "Binary with field tags", "Binary with separate schema"],
                        ["Schema", "No enforced schema", "Required .proto schema with field tags", "Required schema (writer + reader)"],
                        ["Size", "Larger — field names repeated", "Compact — numeric tags", "Most compact — no field identifiers in data"],
                        ["Compatibility", "Flexible but fragile", "Strong backward/forward via tags", "Strong — schema resolution at read time"],
                        ["Schema Evolution", "Add fields freely, no guarantees", "Add optional fields with new tag numbers", "Add fields with defaults, uses schema registry"],
                        ["Best For", "APIs, config files, debugging", "Internal microservice RPC", "Big data pipelines, Hadoop, Kafka"]
                    ]
                },
                "followUpQuestion": "A startup expects frequent schema changes and needs both backward and forward compatibility. Which encoding is most suitable?",
                "options": [
                    {"letter": "A", "text": "Raw JSON with no schema validation"},
                    {"letter": "B", "text": "XML with DTD definitions"},
                    {"letter": "C", "text": "Avro with a schema registry"},
                    {"letter": "D", "text": "CSV with header rows"}
                ],
                "answer": "C",
                "explanation": "Avro with a schema registry provides the best support for frequent schema evolution with both backward and forward compatibility. The schema registry ensures all readers and writers can negotiate compatible schemas dynamically."
            },
            {
                "number": 68,
                "type": "comparison",
                "question": "Compare OLTP vs OLAP workloads:",
                "comparisonData": {
                    "headers": ["Aspect", "OLTP", "OLAP"],
                    "rows": [
                        ["Read Pattern", "Small number of records per query (point lookups)", "Aggregate over large number of records"],
                        ["Write Pattern", "Random-access, low-latency inserts/updates", "Bulk import (ETL) or event stream"],
                        ["Users", "Many end users / web apps", "Few internal analysts"],
                        ["Data Size", "GB to TB", "TB to PB"],
                        ["Storage", "Row-oriented (B-Trees)", "Column-oriented"],
                        ["Example", "User checkout, account update", "Monthly revenue report, trend analysis"]
                    ]
                },
                "followUpQuestion": "Why do data warehouses typically use column-oriented storage instead of row-oriented?",
                "options": [
                    {"letter": "A", "text": "Column stores are easier to implement"},
                    {"letter": "B", "text": "Analytical queries typically scan only a few columns across millions of rows, and column storage enables loading just those columns"},
                    {"letter": "C", "text": "Column stores provide better write performance"},
                    {"letter": "D", "text": "Row stores cannot handle large datasets"}
                ],
                "answer": "B",
                "explanation": "Analytical queries typically aggregate a few columns across millions of rows. Column-oriented storage stores each column contiguously, allowing the query engine to read only the needed columns, dramatically reducing I/O compared to loading entire rows."
            },
            {
                "number": 69,
                "type": "essay",
                "question": "Explain how an LSM-Tree handles a write operation from start to finish. Include the role of the WAL, memtable, SSTables, and compaction in your answer.",
                "modelAnswer": "When a write arrives at an LSM-Tree storage engine, it follows these steps:\n\n1. **Write-Ahead Log (WAL):** The write is first appended to an on-disk append-only log (WAL) for crash recovery. If the system crashes before the memtable is flushed, the WAL can reconstruct recent writes.\n\n2. **Memtable:** The write is then inserted into an in-memory balanced tree structure called a memtable (typically a red-black tree or AVL tree). This keeps keys sorted in memory for fast writes and lookups.\n\n3. **Flush to SSTable:** When the memtable exceeds a size threshold (typically a few MB), it is frozen and written to disk as an immutable Sorted String Table (SSTable). A new empty memtable takes over for incoming writes. The SSTable stores keys in sorted order.\n\n4. **Compaction:** Over time, multiple SSTables accumulate on disk. Background compaction merges these files, discarding deleted keys (tombstones) and old versions, keeping only the latest value for each key. This is similar to mergesort.\n\n5. **Reads:** To read a key, the system first checks the memtable, then the most recent SSTable, then older ones. Bloom filters help avoid unnecessary disk reads for non-existent keys.\n\nThis design makes writes very fast (sequential I/O) at the cost of potentially slower reads (checking multiple SSTables).",
                "explanation": "LSM-Trees optimize writes through sequential appends: WAL ensures durability, memtable provides fast in-memory sorting, SSTables persist sorted data immutably to disk, and compaction reclaims space by merging and deduplicating."
            },
            {
                "number": 70,
                "type": "essay",
                "question": "Describe the CAP theorem and explain why it forces a tradeoff during network partitions. Provide a real-world example of a system choosing availability over consistency.",
                "modelAnswer": "The CAP theorem (Brewer's theorem) states that in a distributed data system, you can guarantee only two out of three properties simultaneously:\n\n- **Consistency (C):** Every read receives the most recent write or an error.\n- **Availability (A):** Every request receives a non-error response (though it may not be the most recent write).\n- **Partition Tolerance (P):** The system continues operating despite network partitions (dropped/delayed messages between nodes).\n\n**Why the tradeoff exists:** Network partitions are inevitable in distributed systems. When a partition occurs, the system must choose:\n- **CP (Consistency over Availability):** Refuse to respond if data might be stale. Example: a banking system that blocks transactions during a partition to prevent double-spending.\n- **AP (Availability over Consistency):** Continue responding with potentially stale data. Example: a social media feed that shows slightly outdated posts rather than displaying an error.\n\n**Real-world example:** Amazon's DynamoDB/Cassandra-style systems choose AP — during a partition, all nodes continue accepting writes using quorum-based consistency. Conflicts are resolved later using last-write-wins (LWW) or vector clocks. This ensures the shopping cart remains available even during network issues, accepting the risk of minor inconsistencies that are reconciled later.",
                "explanation": "The CAP theorem acknowledges that network partitions are unavoidable, so distributed systems must choose between consistency (blocking until data is synchronized) or availability (serving possibly stale data). Most modern systems choose AP with eventual consistency."
            },
            {
                "number": 71,
                "type": "essay",
                "question": "Compare and contrast forward compatibility and backward compatibility in the context of data encoding (Chapter 4). Why are both important for rolling upgrades?",
                "modelAnswer": "**Backward Compatibility:** Newer code can read data written by older code. This is relatively easy to achieve — new code knows about old formats and can handle missing fields by using defaults.\n\n**Forward Compatibility:** Older code can read data written by newer code. This is trickier — the old code must gracefully ignore unknown fields added by the new version without crashing or corrupting data.\n\n**Why both matter for rolling upgrades:**\nIn a large deployment, you cannot upgrade all servers simultaneously. During a rolling upgrade:\n- Some servers run the NEW version, some still run the OLD version\n- New servers write data with new fields → old servers must read it (forward compatibility)\n- Old servers still have data in old format → new servers must read it (backward compatibility)\n\nProtocol Buffers and Avro handle this through field tags and schema evolution rules: new optional fields are ignored by old readers (forward compat), and missing fields get default values for new readers (backward compat).\n\nWithout both forms of compatibility, rolling upgrades would require downtime to upgrade all nodes atomically.",
                "explanation": "Both compatibility directions are essential for zero-downtime rolling deployments where old and new code versions coexist temporarily, reading and writing data in potentially different schema versions."
            },
            {
                "number": 72,
                "type": "comparison",
                "question": "Compare Hash Indexes vs SSTable/LSM-Tree Indexes vs B-Tree Indexes:",
                "comparisonData": {
                    "headers": ["Aspect", "Hash Index", "SSTable/LSM-Tree", "B-Tree"],
                    "rows": [
                        ["Structure", "In-memory hash map → byte offsets", "Sorted on-disk segments + memtable", "Balanced tree of fixed-size pages"],
                        ["Range Queries", "Not supported", "Efficient — keys sorted", "Efficient — keys sorted in pages"],
                        ["Write Speed", "Fast (append-only)", "Very fast (sequential writes)", "Moderate (random page writes)"],
                        ["Read Speed", "O(1) lookups", "O(log n) + check multiple SSTables", "O(log n) single tree traversal"],
                        ["Memory Usage", "Must fit in RAM", "Sparse index in RAM", "Some pages cached in RAM"],
                        ["Crash Recovery", "Rebuild from log", "WAL + immutable SSTables", "WAL + in-place page updates"]
                    ]
                },
                "followUpQuestion": "A system needs to support both exact-key lookups and range scans with very high write throughput. Which index is best?",
                "options": [
                    {"letter": "A", "text": "Hash index — fastest lookups"},
                    {"letter": "B", "text": "B-Tree — balanced performance"},
                    {"letter": "C", "text": "LSM-Tree/SSTable index — sorted keys with fast sequential writes"},
                    {"letter": "D", "text": "No index — full table scan"}
                ],
                "answer": "C",
                "explanation": "LSM-Trees provide both sorted keys (enabling range scans) and sequential write patterns (enabling high write throughput). Hash indexes cannot do range queries, and B-Trees have slower write performance due to random I/O."
            }
        ]
    }
];

export default examData;
