// Autogenerated exam questions data
const examData = [
  {
    "title": "Exam 1: LSM Trees, NoSQL, and Database Concepts",
    "questions": [
      {
        "number": 1,
        "question": "Read amplification:",
        "options": [
          {
            "letter": "A",
            "text": "Cache hit"
          },
          {
            "letter": "B",
            "text": "Fewer reads"
          },
          {
            "letter": "C",
            "text": "Faster reads"
          },
          {
            "letter": "D",
            "text": "More reads needed per query"
          }
        ],
        "answer": "D"
      },
      {
        "number": 2,
        "question": "Schema-on-read is common in:",
        "options": [
          {
            "letter": "A",
            "text": "NoSQL systems"
          },
          {
            "letter": "B",
            "text": "Oracle"
          },
          {
            "letter": "C",
            "text": "Relational DBs"
          },
          {
            "letter": "D",
            "text": "SQL Server"
          }
        ],
        "answer": "A"
      },
      {
        "number": 3,
        "question": "System handles more users but response time increases slightly. This indicates:",
        "options": [
          {
            "letter": "A",
            "text": "Scalability trade-off"
          },
          {
            "letter": "B",
            "text": "Data inconsistency"
          },
          {
            "letter": "C",
            "text": "Poor reliability"
          },
          {
            "letter": "D",
            "text": "System failure"
          }
        ],
        "answer": "A"
      },
      {
        "number": 4,
        "question": "Why are SSTables immutable?",
        "options": [
          {
            "letter": "A",
            "text": "To prevent data loss"
          },
          {
            "letter": "B",
            "text": "To avoid indexing"
          },
          {
            "letter": "C",
            "text": "To reduce disk usage"
          },
          {
            "letter": "D",
            "text": "To simplify concurrency and enable efficient merging"
          }
        ],
        "answer": "D"
      },
      {
        "number": 5,
        "question": "During compaction, duplicate keys are:",
        "options": [
          {
            "letter": "A",
            "text": "Stored twice"
          },
          {
            "letter": "B",
            "text": "Merged, keeping the latest value"
          },
          {
            "letter": "C",
            "text": "Deleted entirely"
          },
          {
            "letter": "D",
            "text": "Ignored"
          }
        ],
        "answer": "B"
      },
      {
        "number": 6,
        "question": "Simplicity helps reduce:",
        "options": [
          {
            "letter": "A",
            "text": "Latency"
          },
          {
            "letter": "B",
            "text": "Complexity"
          },
          {
            "letter": "C",
            "text": "Throughput"
          },
          {
            "letter": "D",
            "text": "Disk usage"
          }
        ],
        "answer": "B"
      },
      {
        "number": 7,
        "question": "What is a tombstone in LSM trees?",
        "options": [
          {
            "letter": "A",
            "text": "Cache entry"
          },
          {
            "letter": "B",
            "text": "Backup file"
          },
          {
            "letter": "C",
            "text": "Marker for deleted data"
          },
          {
            "letter": "D",
            "text": "Index entry"
          }
        ],
        "answer": "C"
      },
      {
        "number": 8,
        "question": "Segment files in LSM:",
        "options": [
          {
            "letter": "A",
            "text": "Are immutable"
          },
          {
            "letter": "B",
            "text": "Deleted immediately"
          },
          {
            "letter": "C",
            "text": "Are mutable"
          },
          {
            "letter": "D",
            "text": "Stored in RAM only"
          }
        ],
        "answer": "A"
      },
      {
        "number": 9,
        "question": "What is a key property of an SSTable?",
        "options": [
          {
            "letter": "A",
            "text": "Keys are encrypted"
          },
          {
            "letter": "B",
            "text": "Keys are compressed"
          },
          {
            "letter": "C",
            "text": "Keys are sorted"
          },
          {
            "letter": "D",
            "text": "Keys are random"
          }
        ],
        "answer": "C"
      },
      {
        "number": 10,
        "question": "Load can be described using:",
        "options": [
          {
            "letter": "A",
            "text": "API version"
          },
          {
            "letter": "B",
            "text": "Load parameters"
          },
          {
            "letter": "C",
            "text": "CPU type"
          },
          {
            "letter": "D",
            "text": "Programming language"
          }
        ],
        "answer": "B"
      },
      {
        "number": 11,
        "question": "What does reliability mean in a system?",
        "options": [
          {
            "letter": "A",
            "text": "Small response time"
          },
          {
            "letter": "B",
            "text": "Fast deployment"
          },
          {
            "letter": "C",
            "text": "Easy debugging"
          },
          {
            "letter": "D",
            "text": "System continues working correctly even if parts fail"
          }
        ],
        "answer": "D"
      },
      {
        "number": 12,
        "question": "LSM Trees are optimized for:",
        "options": [
          {
            "letter": "A",
            "text": "Graph traversal"
          },
          {
            "letter": "B",
            "text": "Random reads"
          },
          {
            "letter": "C",
            "text": "Joins"
          },
          {
            "letter": "D",
            "text": "Writes"
          }
        ],
        "answer": "D"
      },
      {
        "number": 13,
        "question": "LSM trees suffer from:",
        "options": [
          {
            "letter": "A",
            "text": "Slow storage"
          },
          {
            "letter": "B",
            "text": "Read amplification"
          },
          {
            "letter": "C",
            "text": "Low scalability"
          },
          {
            "letter": "D",
            "text": "Poor writes"
          }
        ],
        "answer": "B"
      },
      {
        "number": 14,
        "question": "What happens when a memtable is full?",
        "options": [
          {
            "letter": "A",
            "text": "It is compressed only"
          },
          {
            "letter": "B",
            "text": "It is written to disk as an SSTable"
          },
          {
            "letter": "C",
            "text": "It is cached"
          },
          {
            "letter": "D",
            "text": "It is deleted"
          }
        ],
        "answer": "B"
      },
      {
        "number": 15,
        "question": "Impedance mismatch refers to:",
        "options": [
          {
            "letter": "A",
            "text": "Query optimization"
          },
          {
            "letter": "B",
            "text": "Memory leak"
          },
          {
            "letter": "C",
            "text": "Disk failure"
          },
          {
            "letter": "D",
            "text": "Difference between OOP and relational model"
          }
        ],
        "answer": "D"
      },
      {
        "number": 16,
        "question": "Relational model organizes data into:",
        "options": [
          {
            "letter": "A",
            "text": "Graphs"
          },
          {
            "letter": "B",
            "text": "Trees"
          },
          {
            "letter": "C",
            "text": "Tables"
          },
          {
            "letter": "D",
            "text": "Documents"
          }
        ],
        "answer": "C"
      },
      {
        "number": 17,
        "question": "A fault is:",
        "options": [
          {
            "letter": "A",
            "text": "A single component deviation from expected behavior"
          },
          {
            "letter": "B",
            "text": "A crash report"
          },
          {
            "letter": "C",
            "text": "A system failure"
          },
          {
            "letter": "D",
            "text": "A bug fix"
          }
        ],
        "answer": "A"
      },
      {
        "number": 18,
        "question": "Data locality improves:",
        "options": [
          {
            "letter": "A",
            "text": "Latency"
          },
          {
            "letter": "B",
            "text": "Disk usage"
          },
          {
            "letter": "C",
            "text": "Scalability"
          },
          {
            "letter": "D",
            "text": "Schema"
          }
        ],
        "answer": "A"
      },
      {
        "number": 19,
        "question": "Bloom filter:",
        "options": [
          {
            "letter": "A",
            "text": "Compresses files"
          },
          {
            "letter": "B",
            "text": "Caches queries"
          },
          {
            "letter": "C",
            "text": "Tests membership probabilistically"
          },
          {
            "letter": "D",
            "text": "Sorts data"
          }
        ],
        "answer": "C"
      },
      {
        "number": 20,
        "question": "Hash index works best for:",
        "options": [
          {
            "letter": "A",
            "text": "Range queries"
          },
          {
            "letter": "B",
            "text": "Full scans"
          },
          {
            "letter": "C",
            "text": "Exact match queries"
          },
          {
            "letter": "D",
            "text": "Graph queries"
          }
        ],
        "answer": "C"
      },
      {
        "number": 21,
        "question": "Write amplification means:",
        "options": [
          {
            "letter": "A",
            "text": "Slow replication"
          },
          {
            "letter": "B",
            "text": "Memory optimization"
          },
          {
            "letter": "C",
            "text": "More bytes written than requested"
          },
          {
            "letter": "D",
            "text": "Faster writes"
          }
        ],
        "answer": "C"
      },
      {
        "number": 22,
        "question": "Schema-on-write means:",
        "options": [
          {
            "letter": "A",
            "text": "Dynamic schema"
          },
          {
            "letter": "B",
            "text": "Schema ignored"
          },
          {
            "letter": "C",
            "text": "Schema enforced when writing"
          },
          {
            "letter": "D",
            "text": "Schema removed"
          }
        ],
        "answer": "C"
      },
      {
        "number": 23,
        "question": "When writing to an SSTable system, new data is first:",
        "options": [
          {
            "letter": "A",
            "text": "Stored in cache"
          },
          {
            "letter": "B",
            "text": "Stored in a memtable (in-memory) first"
          },
          {
            "letter": "C",
            "text": "Sent to cache only"
          },
          {
            "letter": "D",
            "text": "Deleted immediately"
          }
        ],
        "answer": "B"
      },
      {
        "number": 24,
        "question": "Which is a document database?",
        "options": [
          {
            "letter": "A",
            "text": "MongoDB"
          },
          {
            "letter": "B",
            "text": "MySQL"
          },
          {
            "letter": "C",
            "text": "PostgreSQL"
          },
          {
            "letter": "D",
            "text": "Oracle"
          }
        ],
        "answer": "A"
      },
      {
        "number": 25,
        "question": "Operability focuses on:",
        "options": [
          {
            "letter": "A",
            "text": "Query optimization"
          },
          {
            "letter": "B",
            "text": "Data compression"
          },
          {
            "letter": "C",
            "text": "Backup only"
          },
          {
            "letter": "D",
            "text": "System monitoring and operation"
          }
        ],
        "answer": "D"
      },
      {
        "number": 26,
        "question": "Denormalization means:",
        "options": [
          {
            "letter": "A",
            "text": "Encrypting data"
          },
          {
            "letter": "B",
            "text": "Duplicating data"
          },
          {
            "letter": "C",
            "text": "Removing data"
          },
          {
            "letter": "D",
            "text": "Compressing data"
          }
        ],
        "answer": "B"
      },
      {
        "number": 27,
        "question": "System is hard to modify when changing requirements. Which property is missing?",
        "options": [
          {
            "letter": "A",
            "text": "Simplicity"
          },
          {
            "letter": "B",
            "text": "Reliability"
          },
          {
            "letter": "C",
            "text": "Rigidity"
          },
          {
            "letter": "D",
            "text": "Evolvability"
          }
        ],
        "answer": "C"
      },
      {
        "number": 28,
        "question": "Bloom filters are used to:",
        "options": [
          {
            "letter": "A",
            "text": "Encrypt data"
          },
          {
            "letter": "B",
            "text": "Compress files"
          },
          {
            "letter": "C",
            "text": "Avoid unnecessary SSTable reads"
          },
          {
            "letter": "D",
            "text": "Improve throughput"
          }
        ],
        "answer": "C"
      },
      {
        "number": 29,
        "question": "Latency means:",
        "options": [
          {
            "letter": "A",
            "text": "Storage size"
          },
          {
            "letter": "B",
            "text": "Data rate"
          },
          {
            "letter": "C",
            "text": "Response time"
          },
          {
            "letter": "D",
            "text": "Throughput"
          }
        ],
        "answer": "C"
      },
      {
        "number": 30,
        "question": "NoSQL databases typically:",
        "options": [
          {
            "letter": "A",
            "text": "Use strict schemas"
          },
          {
            "letter": "B",
            "text": "Require normalization"
          },
          {
            "letter": "C",
            "text": "Avoid joins"
          },
          {
            "letter": "D",
            "text": "Only support SQL"
          }
        ],
        "answer": "C"
      },
      {
        "number": 31,
        "question": "Index is:",
        "options": [
          {
            "letter": "A",
            "text": "Backup system"
          },
          {
            "letter": "B",
            "text": "Data structure to speed up queries"
          },
          {
            "letter": "C",
            "text": "Cache only"
          },
          {
            "letter": "D",
            "text": "Data storage"
          }
        ],
        "answer": "B"
      },
      {
        "number": 32,
        "question": "Normalization reduces:",
        "options": [
          {
            "letter": "A",
            "text": "Redundancy"
          },
          {
            "letter": "B",
            "text": "Speed"
          },
          {
            "letter": "C",
            "text": "Disk usage"
          },
          {
            "letter": "D",
            "text": "Network traffic"
          }
        ],
        "answer": "A"
      },
      {
        "number": 33,
        "question": "A log-structured storage system:",
        "options": [
          {
            "letter": "A",
            "text": "Overwrites data in place"
          },
          {
            "letter": "B",
            "text": "Appends data sequentially"
          },
          {
            "letter": "C",
            "text": "Avoids disks"
          },
          {
            "letter": "D",
            "text": "Uses only RAM"
          }
        ],
        "answer": "B"
      },
      {
        "number": 34,
        "question": "Compaction in LSM trees does:",
        "options": [
          {
            "letter": "A",
            "text": "Splits tables"
          },
          {
            "letter": "B",
            "text": "Merges segments"
          },
          {
            "letter": "C",
            "text": "Deletes database"
          },
          {
            "letter": "D",
            "text": "Encrypts data"
          }
        ],
        "answer": "B"
      },
      {
        "number": 35,
        "question": "Which model is best for many-to-many relationships?",
        "options": [
          {
            "letter": "A",
            "text": "Relational"
          },
          {
            "letter": "B",
            "text": "Column store"
          },
          {
            "letter": "C",
            "text": "Key-value"
          },
          {
            "letter": "D",
            "text": "Document"
          }
        ],
        "answer": "A"
      },
      {
        "number": 36,
        "question": "Scalability refers to:",
        "options": [
          {
            "letter": "A",
            "text": "Database schema"
          },
          {
            "letter": "B",
            "text": "Code readability"
          },
          {
            "letter": "C",
            "text": "Ability to handle increasing load"
          },
          {
            "letter": "D",
            "text": "System size"
          }
        ],
        "answer": "C"
      },
      {
        "number": 37,
        "question": "Graph databases store data as:",
        "options": [
          {
            "letter": "A",
            "text": "Nodes and edges"
          },
          {
            "letter": "B",
            "text": "Tables"
          },
          {
            "letter": "C",
            "text": "Key-value pairs"
          },
          {
            "letter": "D",
            "text": "JSON"
          }
        ],
        "answer": "A"
      },
      {
        "number": 38,
        "question": "Which is NOT a type of fault?",
        "options": [
          {
            "letter": "A",
            "text": "Human error"
          },
          {
            "letter": "B",
            "text": "Data redundancy"
          },
          {
            "letter": "C",
            "text": "Software fault"
          },
          {
            "letter": "D",
            "text": "Hardware fault"
          }
        ],
        "answer": "B"
      },
      {
        "number": 39,
        "question": "A read in LSM tree may require:",
        "options": [
          {
            "letter": "A",
            "text": "Only cache lookup"
          },
          {
            "letter": "B",
            "text": "No disk access"
          },
          {
            "letter": "C",
            "text": "One lookup only"
          },
          {
            "letter": "D",
            "text": "Searching multiple SSTables"
          }
        ],
        "answer": "D"
      },
      {
        "number": 40,
        "question": "Compaction in LSM trees is:",
        "options": [
          {
            "letter": "A",
            "text": "Merging multiple SSTables into one"
          },
          {
            "letter": "B",
            "text": "Caching data"
          },
          {
            "letter": "C",
            "text": "Removing all data"
          },
          {
            "letter": "D",
            "text": "Encrypting SSTables"
          }
        ],
        "answer": "A"
      }
    ]
  },
  {
    "title": "Exam 2: Replication and Distributed Systems",
    "questions": [
      {
        "number": 1,
        "question": "What is the primary goal of replication in distributed systems?",
        "options": [
          {
            "letter": "A",
            "text": "To reduce storage cost"
          },
          {
            "letter": "B",
            "text": "To keep copies of data on multiple nodes"
          },
          {
            "letter": "C",
            "text": "To avoid indexing"
          },
          {
            "letter": "D",
            "text": "To compress files"
          }
        ],
        "answer": "B"
      },
      {
        "number": 2,
        "question": "Which replication model allows all replicas to accept writes?",
        "options": [
          {
            "letter": "A",
            "text": "Single-leader replication"
          },
          {
            "letter": "B",
            "text": "Follower-only replication"
          },
          {
            "letter": "C",
            "text": "Multi-leader replication"
          },
          {
            "letter": "D",
            "text": "Snapshot replication"
          }
        ],
        "answer": "C"
      },
      {
        "number": 3,
        "question": "In leader-based replication, what does the leader do?",
        "options": [
          {
            "letter": "A",
            "text": "Deletes replicas"
          },
          {
            "letter": "B",
            "text": "Coordinates write operations"
          },
          {
            "letter": "C",
            "text": "Handles only reads"
          },
          {
            "letter": "D",
            "text": "Compresses data"
          }
        ],
        "answer": "B"
      },
      {
        "number": 4,
        "question": "What is a follower in replication?",
        "options": [
          {
            "letter": "A",
            "text": "A backup application"
          },
          {
            "letter": "B",
            "text": "A node that copies data changes from the leader"
          },
          {
            "letter": "C",
            "text": "A client-side cache"
          },
          {
            "letter": "D",
            "text": "A query optimizer"
          }
        ],
        "answer": "B"
      },
      {
        "number": 5,
        "question": "What is synchronous replication mainly valued for?",
        "options": [
          {
            "letter": "A",
            "text": "Faster writes"
          },
          {
            "letter": "B",
            "text": "Strong consistency guarantees"
          },
          {
            "letter": "C",
            "text": "Lower disk usage"
          },
          {
            "letter": "D",
            "text": "Reduced memory usage"
          }
        ],
        "answer": "B"
      },
      {
        "number": 6,
        "question": "What is a disadvantage of synchronous replication?",
        "options": [
          {
            "letter": "A",
            "text": "Higher latency"
          },
          {
            "letter": "B",
            "text": "Data duplication"
          },
          {
            "letter": "C",
            "text": "Weak consistency"
          },
          {
            "letter": "D",
            "text": "No failover"
          }
        ],
        "answer": "A"
      },
      {
        "number": 7,
        "question": "What happens in asynchronous replication?",
        "options": [
          {
            "letter": "A",
            "text": "Replication stops completely"
          },
          {
            "letter": "B",
            "text": "All replicas write simultaneously"
          },
          {
            "letter": "C",
            "text": "Replication happens with delay"
          },
          {
            "letter": "D",
            "text": "Followers reject updates"
          }
        ],
        "answer": "C"
      },
      {
        "number": 8,
        "question": "What is replication lag?",
        "options": [
          {
            "letter": "A",
            "text": "Delay in query execution"
          },
          {
            "letter": "B",
            "text": "Delay between leader and follower updates"
          },
          {
            "letter": "C",
            "text": "Delay in backups"
          },
          {
            "letter": "D",
            "text": "Delay in indexing"
          }
        ],
        "answer": "B"
      },
      {
        "number": 9,
        "question": "Why can replication lag be problematic?",
        "options": [
          {
            "letter": "A",
            "text": "It increases storage cost"
          },
          {
            "letter": "B",
            "text": "It may return stale reads"
          },
          {
            "letter": "C",
            "text": "It deletes replicas"
          },
          {
            "letter": "D",
            "text": "It prevents failover"
          }
        ],
        "answer": "B"
      },
      {
        "number": 10,
        "question": "What is eventual consistency?",
        "options": [
          {
            "letter": "A",
            "text": "All replicas fail together"
          },
          {
            "letter": "B",
            "text": "Replicas become consistent over time"
          },
          {
            "letter": "C",
            "text": "Data is always synchronized instantly"
          },
          {
            "letter": "D",
            "text": "Queries are eventually deleted"
          }
        ],
        "answer": "B"
      },
      {
        "number": 11,
        "question": "What is statement-based replication?",
        "options": [
          {
            "letter": "A",
            "text": "Replicating write logs"
          },
          {
            "letter": "B",
            "text": "Replicating snapshots only"
          },
          {
            "letter": "C",
            "text": "Replicating indexes"
          },
          {
            "letter": "D",
            "text": "Replicating caches"
          }
        ],
        "answer": "A"
      },
      {
        "number": 12,
        "question": "What is a challenge with statement-based replication?",
        "options": [
          {
            "letter": "A",
            "text": "High memory usage"
          },
          {
            "letter": "B",
            "text": "Non-deterministic queries can diverge"
          },
          {
            "letter": "C",
            "text": "No write support"
          },
          {
            "letter": "D",
            "text": "Data compression issues"
          }
        ],
        "answer": "B"
      },
      {
        "number": 13,
        "question": "What is write-ahead log (WAL) shipping?",
        "options": [
          {
            "letter": "A",
            "text": "Copying entire databases"
          },
          {
            "letter": "B",
            "text": "Replicating database log records"
          },
          {
            "letter": "C",
            "text": "Encrypting logs"
          },
          {
            "letter": "D",
            "text": "Deleting old logs"
          }
        ],
        "answer": "B"
      },
      {
        "number": 14,
        "question": "What is a drawback of WAL shipping?",
        "options": [
          {
            "letter": "A",
            "text": "It ties replicas to same storage version"
          },
          {
            "letter": "B",
            "text": "It prevents replication"
          },
          {
            "letter": "C",
            "text": "It disables backups"
          },
          {
            "letter": "D",
            "text": "It increases consistency"
          }
        ],
        "answer": "A"
      },
      {
        "number": 15,
        "question": "What is logical log replication?",
        "options": [
          {
            "letter": "A",
            "text": "Replicating binary files"
          },
          {
            "letter": "B",
            "text": "Replicating high-level row changes"
          },
          {
            "letter": "C",
            "text": "Replicating only indexes"
          },
          {
            "letter": "D",
            "text": "Replicating snapshots"
          }
        ],
        "answer": "B"
      },
      {
        "number": 16,
        "question": "What is the CAP-related tradeoff often discussed with replication?",
        "options": [
          {
            "letter": "A",
            "text": "Consistency versus availability during partitions"
          },
          {
            "letter": "B",
            "text": "Storage versus memory"
          },
          {
            "letter": "C",
            "text": "CPU versus GPU"
          },
          {
            "letter": "D",
            "text": "Security versus backups"
          }
        ],
        "answer": "A"
      },
      {
        "number": 17,
        "question": "What is a snapshot in replication?",
        "options": [
          {
            "letter": "A",
            "text": "A query optimizer"
          },
          {
            "letter": "B",
            "text": "A copy of database state at a moment in time"
          },
          {
            "letter": "C",
            "text": "A replication delay"
          },
          {
            "letter": "D",
            "text": "A temporary cache"
          }
        ],
        "answer": "B"
      },
      {
        "number": 18,
        "question": "Why are snapshots useful?",
        "options": [
          {
            "letter": "A",
            "text": "They reduce CPU usage"
          },
          {
            "letter": "B",
            "text": "They help initialize new followers"
          },
          {
            "letter": "C",
            "text": "They compress logs"
          },
          {
            "letter": "D",
            "text": "They remove replicas"
          }
        ],
        "answer": "B"
      },
      {
        "number": 19,
        "question": "What is failover?",
        "options": [
          {
            "letter": "A",
            "text": "Deleting a leader"
          },
          {
            "letter": "B",
            "text": "Promoting a follower when leader fails"
          },
          {
            "letter": "C",
            "text": "Compressing data"
          },
          {
            "letter": "D",
            "text": "Rebuilding indexes"
          }
        ],
        "answer": "B"
      },
      {
        "number": 20,
        "question": "What is a risk during failover?",
        "options": [
          {
            "letter": "A",
            "text": "Faster writes"
          },
          {
            "letter": "B",
            "text": "Data loss of unreplicated writes"
          },
          {
            "letter": "C",
            "text": "Reduced storage"
          },
          {
            "letter": "D",
            "text": "Improved consistency"
          }
        ],
        "answer": "B"
      },
      {
        "number": 21,
        "question": "What is split-brain?",
        "options": [
          {
            "letter": "A",
            "text": "Two leaders accepting writes independently"
          },
          {
            "letter": "B",
            "text": "One replica shutting down"
          },
          {
            "letter": "C",
            "text": "Disk corruption"
          },
          {
            "letter": "D",
            "text": "Query timeout"
          }
        ],
        "answer": "A"
      },
      {
        "number": 22,
        "question": "What is multi-leader replication useful for?",
        "options": [
          {
            "letter": "A",
            "text": "Single-user systems"
          },
          {
            "letter": "B",
            "text": "Multi-datacenter setups"
          },
          {
            "letter": "C",
            "text": "File compression"
          },
          {
            "letter": "D",
            "text": "Read-only systems"
          }
        ],
        "answer": "B"
      },
      {
        "number": 23,
        "question": "What is a conflict in multi-leader replication?",
        "options": [
          {
            "letter": "A",
            "text": "Missing replicas"
          },
          {
            "letter": "B",
            "text": "Different replicas modifying same data differently"
          },
          {
            "letter": "C",
            "text": "Low storage capacity"
          },
          {
            "letter": "D",
            "text": "Slow indexing"
          }
        ],
        "answer": "B"
      },
      {
        "number": 24,
        "question": "How are conflicts commonly resolved?",
        "options": [
          {
            "letter": "A",
            "text": "Deleting all replicas"
          },
          {
            "letter": "B",
            "text": "Using conflict resolution strategies"
          },
          {
            "letter": "C",
            "text": "Ignoring updates"
          },
          {
            "letter": "D",
            "text": "Restarting servers"
          }
        ],
        "answer": "B"
      },
      {
        "number": 25,
        "question": "What is one downside of multi-leader replication?",
        "options": [
          {
            "letter": "A",
            "text": "No scalability"
          },
          {
            "letter": "B",
            "text": "More conflict handling complexity"
          },
          {
            "letter": "C",
            "text": "No failover"
          },
          {
            "letter": "D",
            "text": "Lower consistency guarantees"
          }
        ],
        "answer": "B"
      },
      {
        "number": 26,
        "question": "What is leaderless replication?",
        "options": [
          {
            "letter": "A",
            "text": "Replication without any coordinator leader"
          },
          {
            "letter": "B",
            "text": "Replication with one leader only"
          },
          {
            "letter": "C",
            "text": "Replication using snapshots"
          },
          {
            "letter": "D",
            "text": "Replication without followers"
          }
        ],
        "answer": "A"
      },
      {
        "number": 27,
        "question": "Which system popularized leaderless replication?",
        "options": [
          {
            "letter": "A",
            "text": "MongoDB"
          },
          {
            "letter": "B",
            "text": "Dynamo"
          },
          {
            "letter": "C",
            "text": "Oracle"
          },
          {
            "letter": "D",
            "text": "MySQL"
          }
        ],
        "answer": "B"
      },
      {
        "number": 28,
        "question": "What does quorum mean in leaderless replication?",
        "options": [
          {
            "letter": "A",
            "text": "Number of disks"
          },
          {
            "letter": "B",
            "text": "Minimum number of nodes required for reads/writes"
          },
          {
            "letter": "C",
            "text": "Number of users"
          },
          {
            "letter": "D",
            "text": "Number of backups"
          }
        ],
        "answer": "B"
      },
      {
        "number": 29,
        "question": "What is the condition often used for strong quorum consistency?",
        "options": [
          {
            "letter": "A",
            "text": "r + w > n"
          },
          {
            "letter": "B",
            "text": "r = w"
          },
          {
            "letter": "C",
            "text": "n < w"
          },
          {
            "letter": "D",
            "text": "r - w = n"
          }
        ],
        "answer": "A"
      },
      {
        "number": 30,
        "question": "What does ‘n’ represent in quorum systems?",
        "options": [
          {
            "letter": "A",
            "text": "Number of clients"
          },
          {
            "letter": "B",
            "text": "Number of replicas"
          },
          {
            "letter": "C",
            "text": "Number of queries"
          },
          {
            "letter": "D",
            "text": "Number of leaders"
          }
        ],
        "answer": "B"
      },
      {
        "number": 31,
        "question": "What is sloppy quorum?",
        "options": [
          {
            "letter": "A",
            "text": "Queries without indexes"
          },
          {
            "letter": "B",
            "text": "Writes accepted by temporary nodes"
          },
          {
            "letter": "C",
            "text": "Delayed snapshots"
          },
          {
            "letter": "D",
            "text": "Synchronous writes"
          }
        ],
        "answer": "B"
      },
      {
        "number": 32,
        "question": "What is hinted handoff?",
        "options": [
          {
            "letter": "A",
            "text": "Deleting old replicas"
          },
          {
            "letter": "B",
            "text": "Later forwarding temporarily stored writes"
          },
          {
            "letter": "C",
            "text": "Compressing snapshots"
          },
          {
            "letter": "D",
            "text": "Ignoring replication failures"
          }
        ],
        "answer": "B"
      },
      {
        "number": 33,
        "question": "What problem can occur in leaderless replication during concurrent writes?",
        "options": [
          {
            "letter": "A",
            "text": "Clock drift and write conflicts"
          },
          {
            "letter": "B",
            "text": "Query optimization"
          },
          {
            "letter": "C",
            "text": "Cache overflow"
          },
          {
            "letter": "D",
            "text": "File corruption"
          }
        ],
        "answer": "A"
      },
      {
        "number": 34,
        "question": "Why are vector clocks used?",
        "options": [
          {
            "letter": "A",
            "text": "To improve compression"
          },
          {
            "letter": "B",
            "text": "To detect causality and concurrent updates"
          },
          {
            "letter": "C",
            "text": "To encrypt replication logs"
          },
          {
            "letter": "D",
            "text": "To reduce storage"
          }
        ],
        "answer": "B"
      }
    ]
  }
];

export default examData;
