import re
import json

def parse_questions_file(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    # We only want the Multiple Choice Questions section (from the start until the Q&A section)
    mc_section = content.split("Questions and Answers: Designing")[0]
    
    # Split content into lines and clean up empty trailing lines
    lines = [line.strip() for line in mc_section.split("\n")]
    
    questions = []
    
    current_q = None
    collecting_explanation = False
    explanation_lines = []
    
    # Regex to detect Question start, e.g. "Q1. What are..." or "Q10. What is..." or "Q55. What are..."
    q_regex = re.compile(r"^Q(\d+)\.\s*(.*)$", re.IGNORECASE)
    # Option regex, e.g. "A. Speed, cost..." or "B. Reliability..."
    opt_regex = re.compile(r"^([A-D])\.\s*(.*)$", re.IGNORECASE)
    # Answer regex, e.g. "Answer: B"
    ans_regex = re.compile(r"^Answer:\s*([A-D])$", re.IGNORECASE)
    # Explanation starts with "Explanation:"
    exp_regex = re.compile(r"^Explanation:\s*(.*)$", re.IGNORECASE)
    
    for line in lines:
        if not line:
            continue
            
        # Check if new question
        q_match = q_regex.match(line)
        if q_match:
            if current_q:
                # Save previous question
                if collecting_explanation:
                    current_q["explanation"] = " ".join(explanation_lines).strip()
                questions.append(current_q)
            
            q_num = int(q_match.group(1))
            q_text = q_match.group(2)
            
            current_q = {
                "number": q_num,
                "question": q_text,
                "options": [],
                "answer": "",
                "explanation": ""
            }
            collecting_explanation = False
            explanation_lines = []
            continue
            
        if not current_q:
            # Skip any preliminary lines
            continue
            
        # Check if option
        opt_match = opt_regex.match(line)
        if opt_match and not collecting_explanation:
            current_q["options"].append({
                "letter": opt_match.group(1).upper(),
                "text": opt_match.group(2).strip()
            })
            continue
            
        # Check if Answer
        ans_match = ans_regex.match(line)
        if ans_match:
            current_q["answer"] = ans_match.group(1).upper()
            continue
            
        # Check if Explanation start
        exp_match = exp_regex.match(line)
        if exp_match:
            collecting_explanation = True
            explanation_lines = [exp_match.group(1).strip()]
            continue
            
        # If collecting explanation and line doesn't match above, append to explanation text
        if collecting_explanation:
            explanation_lines.append(line)
        else:
            # If we have already started collecting options, but haven't got the answer yet, 
            # this line must be a continuation of the last option!
            if current_q["options"] and not current_q["answer"]:
                current_q["options"][-1]["text"] += " " + line
            else:
                # If we're not collecting explanation and it's not a option/answer/q, it might be a multi-line question text!
                current_q["question"] += " " + line
            
    # Add final question
    if current_q:
        if collecting_explanation:
            current_q["explanation"] = " ".join(explanation_lines).strip()
        questions.append(current_q)
        
    return questions

def main():
    questions = parse_questions_file("d:/examsWebsite/advWeb/questions 2")
    
    print(f"Successfully parsed {len(questions)} multiple choice questions!")
    
    # Verify we got exactly 65 questions
    for q in questions[:3]:
        print(f"Q{q['number']}: {q['question']}")
        print(f"Options: {q['options']}")
        print(f"Answer: {q['answer']}")
        print("---")
        
    # Group into Exam 1 (Questions 1-30) and Exam 2 (Questions 31-65)
    exam1_qs = [q for q in questions if q["number"] <= 30]
    exam2_qs = [q for q in questions if q["number"] > 30]
    
    print(f"Exam 1 count: {len(exam1_qs)} questions.")
    print(f"Exam 2 count: {len(exam2_qs)} questions.")
    
    exam_data = [
        {
            "examId": 0,
            "title": "Exam 1: Foundations of Data Systems (Chapters 1-3)",
            "questions": exam1_qs
        },
        {
            "examId": 1,
            "title": "Exam 2: Distributed Data & Replication (Chapters 4-5)",
            "questions": exam2_qs
        }
    ]
    
    # Write questions.js with ES6 export
    output_js_path = "d:/examsWebsite/questions.js"
    with open(output_js_path, "w", encoding="utf-8") as out:
        out.write("// Autogenerated from questions 2 using parse_questions.py\n")
        out.write("const examData = ")
        json.dump(exam_data, out, indent=4, ensure_ascii=False)
        out.write(";\n\nexport default examData;\n")
        
    print(f"Successfully wrote questions database to {output_js_path}!")

if __name__ == "__main__":
    main()
